name: documentation
on:
  release:
    types: [published]

jobs:
  build-doc:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - name: Install dependencies
        run: |
          python3 -m pip install -r doc/requirements.txt
          sudo apt-get install -y \
            cmake \
            ninja-build \
            doxygen
      - name: Sphinx build
        run: |
          cmake --preset doc
          cmake --build build/doc
      - name: Upload static files as artifact
        id : upload-artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: build/doc/html
  deploy-doc:
    needs: build-doc
    runs-on: ubuntu-24.04
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
